version: "3"
services:
  generator:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./output:/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
