version: "3"
services:
  generator:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./tmp:/ROOT/tmp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    ports:
      - 8000:8000
