version: "3"
services:
  generator:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - /root/GroundingDINO
      - ./main.py:/root/main.py
      - ./utils.py:/root/utils.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
