version: '3'
services:
  main:
    build:
      dockerfile: Dockerfile
      context: ./
    volumes:
      - ./main.py:/ROOT/main.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    env_file:
      - .env
  face_rec_model:
    build:
      dockerfile: Dockerfile
      context: ./face_rec_model
    volumes:
      - ./face_rec_model/output:/output
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]